name: Python3.10.8 
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - pip
  - python=3.9.*      
  - python-dateutil
  - pytz
  - scikit-learn
  - scipy
  - statsmodels
  - xlrd
  - openpyxl
  - lxml
  - html5lib
  - beautifulsoup4
  - jupyter
  - pip:
    - pmdarima        
    - pytorch
    - keras
